#!/bin/bash

ctags -R *

CSCOPE_DIR="$PWD/cscope"

if [ ! -d "$CSCOPE_DIR" ]; then
mkdir "$CSCOPE_DIR"
fi

if [ -d "$PWD/src" ]
then
echo "Finding files ..."
find "$PWD/src" -name '*.c' \
-o -name '*.h' \
-o -name '*.cpp' \
-o -name '*.hpp' > "$CSCOPE_DIR/cscope.files"

echo "Adding files to cscope db: $PWD/cscope.db ..."
cscope -b -i "$CSCOPE_DIR/cscope.files"

export CSCOPE_DB="$PWD/cscope.out"
echo "Exported CSCOPE_DB to: '$CSCOPE_DB'"
fi
